//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.17 at 11:21:15 AM MSK
//


package com.demo.autogenerated;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.demo.autogenerated package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.demo.autogenerated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCookieResponse }
     * 
     */
    public GetCookieResponse createGetCookieResponse() {
        return new GetCookieResponse();
    }

    /**
     * Create an instance of {@link DeleteCookieRequest }
     * 
     */
    public DeleteCookieRequest createDeleteCookieRequest() {
        return new DeleteCookieRequest();
    }

    /**
     * Create an instance of {@link GetCookieResponse.Cookies }
     * 
     */
    public GetCookieResponse.Cookies createGetCookieResponseCookies() {
        return new GetCookieResponse.Cookies();
    }

    /**
     * Create an instance of {@link CreateCookieResponse }
     * 
     */
    public CreateCookieResponse createCreateCookieResponse() {
        return new CreateCookieResponse();
    }

    /**
     * Create an instance of {@link CreateCookieRequest }
     * 
     */
    public CreateCookieRequest createCreateCookieRequest() {
        return new CreateCookieRequest();
    }

    /**
     * Create an instance of {@link GetCookieRequest }
     * 
     */
    public GetCookieRequest createGetCookieRequest() {
        return new GetCookieRequest();
    }

    /**
     * Create an instance of {@link UpdateCookieRequest }
     * 
     */
    public UpdateCookieRequest createUpdateCookieRequest() {
        return new UpdateCookieRequest();
    }

    /**
     * Create an instance of {@link UpdateCookieResponse }
     * 
     */
    public UpdateCookieResponse createUpdateCookieResponse() {
        return new UpdateCookieResponse();
    }

    /**
     * Create an instance of {@link DeleteCookieResponse }
     * 
     */
    public DeleteCookieResponse createDeleteCookieResponse() {
        return new DeleteCookieResponse();
    }

    /**
     * Create an instance of {@link Cookie }
     * 
     */
    public Cookie createCookie() {
        return new Cookie();
    }

}
