//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.17 at 10:48:27 AM MSK
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://demo.com/autogenerated", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo.autogenerated;
