package com.demo.labsoap.service;

import com.demo.autogenerated.Cookie;
import com.demo.labsoap.dao.CookieDao;
import com.demo.labsoap.exceptions.ValidationException;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class CookieService {
    
    @Autowired
    private CookieDao cookieDao;
    
    public Cookie getCookieById(int id) {
        return cookieDao.getCookieById(id);
    }
    
    public List<Cookie> getCookieByParams(Integer id, String weight, String name, String radius, String country) throws ValidationException {
        return cookieDao.getCookieByParams(id, weight, name, radius, country);
    }
    
    public int createCookie(String weight, String name, String radius, String country) {
        return cookieDao.insertCookie(weight, name, radius, country);
    }
    
    public void modifyCookie(Integer id, String weight, String name, String radius, String country) throws ValidationException {
        cookieDao.modifyCookie(id, weight, name, radius, country);
    }
    
    public void deleteCookie(Integer id) throws ValidationException {
        cookieDao.deleteCookie(id);
    }
}
